apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    throttle: t1
spec:
  schedulerName: my-scheduler
  containers:
  - name: ctr
    image: busybox
    command: ["sleep", "10000"]
    resources:
      requests:
        cpu: 300m
