apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: throttles.schedule.k8s.everpeace.github.com
spec:
  group: schedule.k8s.everpeace.github.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
  scope: Namespaced
  names:
    plural: throttles
    singular: throttle
    kind: Throttle
    shortNames:
    - thr
    - thrs
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: throttled
      JSONPath: .status.throttled
      format: byte
      type: string
    - name: calculatedThreshold
      JSONPath: .status.calculatedThreshold.threshold
      format: byte
      type: string
      priority: 1
    - name: calculatedAt
      JSONPath: .status.calculatedThreshold.calculatedAt
      format: date
      type: date
      priority: 1
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - selector
          - threshold
          properties:
            selector:
              type: object
              required:
                - selectorTerms
              properties:
                selectorTerms:
                  type: array
                  items:
                    type: object
                    properties:
                      podSelector:
                        type: object
            threshold:
              type: object
              properties:
                resourceCounts:
                  type: object
                  properties:
                    pod:
                      type: integer
                resourceRequests:
                  type: object
            temporaryThresholdOverrides:
              type: array
              items:
                type: object
                required:
                  - begin
                  - end
                  - threshold
                properties:
                  begin:
                    description: start time string in RFC3339 for this override entry
                    type: string
                    minLength: 1
                  end:
                    description: end time string in RFC3339 for this override entry
                    type: string
                    minLength: 1
                  threshold:
                    type: object
                    properties:
                      resourceCounts:
                        type: object
                        properties:
                          pod:
                            type: integer
                      resourceRequests:
                        type: object
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusterthrottles.schedule.k8s.everpeace.github.com
spec:
  group: schedule.k8s.everpeace.github.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
  scope: Cluster
  names:
    plural: clusterthrottles
    singular: clusterthrottle
    kind: ClusterThrottle
    shortNames:
    - clthr
    - clthrs
  subresources:
    status: {}
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          type: object
          required:
          - selector
          - threshold
          properties:
            selector:
              type: object
              required:
              - selectorTerms
              properties:
                selectorTerms:
                  type: array
                  items:
                    type: object
                    properties:
                      namespaceSelector:
                        type: object
                      podSelector:
                        type: object
            threshold:
              type: object
              properties:
                resourceCounts:
                  type: object
                  properties:
                    pod:
                      type: integer
                resourceRequests:
                  type: object
            temporaryThresholdOverrides:
              type: array
              items:
                type: object
                required:
                  - begin
                  - end
                  - threshold
                properties:
                  begin:
                    description: start time string in RFC3339 for this override entry
                    type: string
                    minLength: 1
                  end:
                    description: end time string in RFC3339 for this override entry
                    type: string
                    minLength: 1
                  threshold:
                    type: object
                    properties:
                      resourceCounts:
                        type: object
                        properties:
                          pod:
                            type: integer
                      resourceRequests:
                        type: object
